name: "dBUB"
author: SamV522
description: "A simple plugin to bridge users groups between an online database and a minecraft server"
version: "1.2.3"
main: me.SamV522.dBUB.Main
permissions:
    dbub.*:
        description: 'Gives access to all doorman commands'
        children:
            dbub.reload: true
            dbub.version: true
            dbub.help: true
            dbub.sync: true
            dbub.syncdb: true
    dbub.reload:
        description: Reloads dBUB
        default: op
    dbub.version:
        description: 'Shows the user which version of dBUB is running'
        default: op
    dbub.version:
        description: "Shows the user their available commands"
        default: op
    dbub.sync:
        description: "Manually synchronize groups from the database"
        default: op
    #dbub.syncdb:
    #   description: "Manually synchronize groups to the database"
    #   default: op
commands:
    dbub:
      description: 'Master command for dBUB'
      usage: '/dbub [reload/version/help/?/sync/syncdb]'
      permission-message: "You don't have <permission>"